### ISSUE TITLE
Build example workspace (or any other) in its own private install-space

### ISSUE THREAD

**Issue by meyerj** [Intermodalics/ros_android#108]
I did not like the fact that the `example_workspace`, when building with `--samples`, installs to the same install prefix as the system libs and core ROS packages. In my opinion this install-space should stay free of example code and could also be copied between containers and systems to save some time, e.g. when working in a team.

The same applies to any other workspace that could be built with `build_catkin_workspace.sh`. The script is universal enough to be used by users directly, if it would source the `config.sh` script on its own.

I have a version that adds an `--extend` argument to [build_catkin_workspace.sh](https://github.com/Intermodalics/ros_android/blob/kinetic/scripts/build_catkin_workspace.sh) and changes the default install prefix to `workspace/install`, which would be the default with catkin. There is no problem with that approach, but the `CMAKE_FIND_ROOT_PATH` must list all underlay workspaces.

I don't have time right now to cleanup the patch and submit a PR. I will do so next week. Just wanted to hear your opinion first, @jubeira and @ivanpauno.

**Comment by ivanpauno** [comment]
LGTM
I think also it would be nice to move back build_catking_workspace.sh script to the top level dir and add usage to the readme file.
As the only case we set the install prefix to the target dir is when we are building the core catkin_ws, this should be available as an extra argument, and the default behavior should be install in workspace/install.

**Comment by jubeira** [comment]
Sounds good @meyerj; perhaps the last refactor didn't take into account this use case so much, so I agree it's a good idea.

Adding an argument for the install space and making `workspace/install` the default would also work for me.

> The same applies to any other workspace that could be built with build_catkin_workspace.sh. The script is universal enough to be used by users directly, if it would source the config.sh script on its own.

I usually source the config if I need to use a script outside the main entrypoint, but I wouldn't mind sourcing the config on each script as before either. The latter option would assume that the config script is in a fixed position wrt. every other script, but it's not a huge deal anyways.
