### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by gongyue666** [Intermodalics/ros_android#114]
error 1:about uuid, 

`/opt/android/sdk/android-ndk-r18b/sysroot/usr/include/stdint.h:67:
:23:/opt/android/sdk/android-ndk-r18b/sysroot/usr/include/stdint.h :67:23: error: error: typedeftypedef redefinition
      with different types ('__int64_t' (aka 'long') vs 'long long')
 redefinition
      with different types ('__int64_t' (aka 'long') vs 'long long')
typedef __int64_t     int64_t;
                      ^typedef __int64_t     int64_t;

/opt/ros_android/libs/uuid/include/uuid/uuid_types.h:20:                      ^
31/opt/ros_android/libs/uuid/include/uuid/uuid_types.h:: 20:31: note: noteprevious:  definitionprevious is here
 definition is here
typedef __signed__ long long    int64_t;typedef __signed__ long long    int64_t;
                                ^

                                ^
In file included from In file included from /opt/ros_android/libs/uuid/copy.c/opt/ros_android/libs/uuid/compare.c:35:37:
In file included from :
In file included from /opt/ros_android/libs/uuid/uuidP.h:/opt/ros_android/libs/uuid/uuidP.h40::
40In file included from :
/opt/android/sdk/android-ndk-r18b/sysroot/usr/include/sys/types.h:In file included from /opt/android/sdk/android-ndk-r18b/sysroot/usr/include/sys/types.h33::
In file included from /opt/android/sdk/android-ndk-r18b/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/7.0.2/include/stdint.h33:
In file included from /opt/android/sdk/android-ndk-r18b/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/7.0.2/include/stdint.h:63::
63:
/opt/android/sdk/android-ndk-r18b/sysroot/usr/include/stdint.h:/opt/android/sdk/android-ndk-r18b/sysroot/usr/include/stdint.h68::23: error: typedef redefinition68:23: error: typedef redefinition
      with
       differentwith  types ('__uint64_t' (aka 'unsigned long') vs 'unsigned long long')
typedef __uint64_t    uint64_t;
different types ('__uint64_t' (aka 'unsigned long') vs 'unsigned long long')
typedef __uint64_t    uint64_t;                      ^

                      ^
/opt/ros_android/libs/uuid/include/uuid/uuid_types.h/opt/ros_android/libs/uuid/include/uuid/uuid_types.h:24:28::24: 28:note note: previous definition: previous  isdefinition  hereis 
heretypedef unsigned long long      uint64_t;

typedef unsigned long long      uint64_t;
                                ^
In file included from /opt/ros_android/libs/uuid/isnull.c                                ^
:35:
In file included from /opt/ros_android/libs/uuid/uuidP.h:40:
In file included from /opt/android/sdk/android-ndk-r18b/sysroot/usr/include/sys/types.h:33:
In file included from /opt/android/sdk/android-ndk-r18b/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/7.0.2/include/stdint.h:63:
/opt/android/sdk/android-ndk-r18b/sysroot/usr/include/stdint.h:67:23: error: typedef redefinition
      with different types ('__int64_t' (aka 'long') vs 'long long')
typedef __int64_t     int64_t;
                      ^
/opt/ros_android/libs/uuid/include/uuid/uuid_types.h:20:31: note: previous definition is here
typedef __signed__ long long    int64_t;
                                ^
In file included from /opt/ros_android/libs/uuid/isnull.c:35:
In file included from /opt/ros_android/libs/uuid/uuidP.h:40:
In file included from /opt/android/sdk/android-ndk-r18b/sysroot/usr/include/sys/types.h:33:
In file included from /opt/android/sdk/android-ndk-r18b/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/7.0.2/include/stdint.h:63:
/opt/android/sdk/android-ndk-r18b/sysroot/usr/include/stdint.h:68:23: error: typedef redefinition
      with different types ('__uint64_t' (aka 'unsigned long') vs 'unsigned long long')
typedef __uint64_t    uint64_t;
                      ^
/opt/ros_android/libs/uuid/include/uuid/uuid_types.h:24:28: note: previous definition is here
typedef unsigned long long      uint64_t;
                                ^
/opt/ros_android/libs/uuid/gen_uuid.c:159:10: warning: implicit declaration of function 'getpid' is
      invalid in C99 [-Wimplicit-function-declaration]
                srand((getpid() << 16) ^ getuid() ^ tv.tv_sec ^ tv.tv_usec);
                       ^
/opt/ros_android/libs/uuid/gen_uuid.c:159:28: warning: implicit declaration of function 'getuid' is
      invalid in C99 [-Wimplicit-function-declaration]
                srand((getpid() << 16) ^ getuid() ^ tv.tv_sec ^ tv.tv_usec);
                                         ^
/opt/ros_android/libs/uuid/gen_uuid.c:187:8: warning: implicit declaration of function 'read' is
      invalid in C99 [-Wimplicit-function-declaration]
                        i = read(fd, cp, n);
                            ^
/opt/ros_android/libs/uuid/gen_uuid.c:331:4: warning: implicit declaration2  errorofs  generated.
2 errors generated.
2 errors generated.
function 'close' is
      invalid in C99 [-Wimplicit-function-declaration]
                        close(state_fd);
                        ^
CMakeFiles/uuid.dir/build.make:110: recipe for target 'CMakeFiles/uuid.dir/copy.c.o' failed
make[2]: *** [CMakeFiles/uuid.dir/copy.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/opt/ros_android/libs/uuid/gen_uuid.cCMakeFiles/uuid.dir/build.make:158: recipe for target 'CMakeFiles/uuid.dir/isnull.c.o' failed
make[2]: *** [CMakeFiles/uuid.dir/isnull.c.o] Error 1
:346:4: warningCMakeFiles/uuid.dir/build.make:86: recipe for target 'CMakeFiles/uuid.dir/compare.c.o' failed
make[2]: *** [CMakeFiles/uuid.dir/compare.c.o] Error 1
: implicit declaration of function 'close' is
      invalid in C99 [-Wimplicit-function-declaration]
                        close(state_fd);
                        ^
/opt/ros_android/libs/uuid/gen_uuid.c:408:7: warning: implicit declaration of function 'ftruncate' is
      invalid in C99 [-Wimplicit-function-declaration]
                if (ftruncate(state_fd, len) < 0) {
                    ^
/opt/ros_android/libs/uuid/gen_uuid.c:431:9: warning: implicit declaration of function 'read' is
      invalid in C99 [-Wimplicit-function-declaration]
                ret = read(fd, buf, count);
                      ^
/opt/ros_android/libs/uuid/gen_uuid.c:468:3: warning: implicit declaration of function 'close' is
      invalid in C99 [-Wimplicit-function-declaration]
                close(i);
                ^
8 warnings generated.
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/uuid.dir/all' failed
make[1]: *** [CMakeFiles/uuid.dir/all] Error 2
`

what I did is comment off these lines in uuid_types.h
`
#if (!defined(_STDINT_H) && !defined(_UUID_STDINT_H))
#define _UUID_STDINT_H

typedef unsigned char uint8_t;
typedef signed char int8_t;

#if (4 == 8)
// typedef int		int64_t_;
// typedef unsigned int	uint64_t;
#elif (4 == 8)
// typedef long		int64_t;
// typedef unsigned long	uint64_t;
#elif (8 == 8)
#if defined(__GNUC__)
// typedef __signed__ long long 	int64_t;
#else
// typedef signed long long 	int64_t_;
#endif
// typedef unsigned long long	uint64_t;
#endif

#if (4 == 2)
typedef	int		int16_t;
typedef	unsigned int	uint16_t;
#elif (2 == 2)
typedef	short		int16_t;
typedef	unsigned short	uint16_t;
#else
  ?==error: undefined 16 bit type
#endif

#if (4 == 4)
typedef	int		int32_t;
typedef	unsigned int	uint32_t;
#elif (4 == 4)
typedef	long		int32_t;
typedef	unsigned long	uint32_t;
#elif (2 == 4)
typedef	short		int32_t;
typedef	unsigned short	uint32_t;
#else
 ?== error: undefined 32 bit type
#endif

#endif
`

**Comment by gongyue666** [comment]
error 2: about poco:

log:
Building poco.

Unknown configuration: Android_Static
Please use the --config option to specify another build configuration
The following configurations are available:
AIX		     Darwin32		    Linux-clang     SunOS-SunStudio
ARM-Linux	     Darwin32-clang	    MinGW	    SunOS-SunStudio11
Alpine		     Darwin32-clang-libc++  MinGW-CrossEnv  SunOS-stdcxx-x86_64
Android		     Darwin64		    NIOS2-Linux     WatchOS
Angstrom	     Darwin64-clang	    OSF1	    WatchSimulator
AppleTV		     Darwin64-clang-libc++  OpenPandora     Yocto
AppleTVSimulator     DigiEL		    PPC-Linux	    iPhone
BeagleBoard	     ELDK		    QNX		    iPhone-clang
CEGCCARM	     FreeBSD		    SH-Linux	    iPhone-clang-libc++
CYGWIN		     FreeBSD-Linux-compat   SSV-LINUX	    iPhoneSimulator
CygLinux	     GCCEMBEDLINUX	    SmartOS-gcc     iPhoneSimulator-clang
Darwin		     HP-UX		    SunOS	    iPhoneSimulator-clang-libc++
Darwin-clang	     Linux		    SunOS-GCC
Darwin-clang-libc++  Linux-SolarisStudio    SunOS-SunForte
---
I edit the build_library_with_toolchain.sh line 51:
 from " configure_options="--config=Android_Static --no-samples --no-tests"
to " configure_options="--config=Android --no-samples --no-tests"
and then it say:
Configured for Android
/opt/ros_android/libs/poco/build/config/Android:28: *** Invalid ABI specified in ANDROID_ABI.  Stop.
/opt/ros_android/scripts/build_library_with_toolchain.sh poco
---
I add export ANDROID_ABI=armeabi-v7a in build_library_with_toolchain.sh at begining and modity debugging=1 in install.sh (debugging=0) will make poco build error too.

**Comment by gongyue666** [comment]
error 3: about curl 
log:
checking host system type... Invalid configuration `*-linux-android': machine `*' not recognized
configure: error: /bin/bash ./config.sub *-linux-android failed
---
change 
from host=$(basename $prefix/toolchain/*-linux-android)
tp host=$(basename $prefix/toolchain/arm-linux-android)

**Comment by gongyue666** [comment]
error 4: about urdfdom
log:
CMakeFiles/urdf_unit_test.dir/test/urdf_unit_test.cpp.o: In function `main':
urdf_unit_test.cpp:(.text.main+0x14): undefined reference to `boost::unit_test::unit_test_main(bool (*)(), int, char**)'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
urdf_parser/CMakeFiles/urdf_unit_test.dir/build.make:103: recipe for target 'urdf_parser/urdf_unit_test' failed
make[2]: *** [urdf_parser/urdf_unit_test] Error 1
CMakeFiles/Makefile2:210: recipe for target 'urdf_parser/CMakeFiles/urdf_unit_test.dir/all' failed
make[1]: *** [urdf_parser/CMakeFiles/urdf_unit_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Linking CXX executable check_urdf
[100%] Built target check_urdf
Makefile:138: recipe for target 'all' failed
---
update to 1.0.3

**Comment by gongyue666** [comment]
error 5: about pcl
log:
 Could NOT find LIBUSB_1 (missing:  LIBUSB_1_LIBRARY LIBUSB_1_INCLUDE_DIR) 
-- Checking for module 'libusb-1.0'
--   No package 'libusb-1.0' found
-- Could NOT find USB_10 (missing:  USB_10_LIBRARY USB_10_INCLUDE_DIR) 
-- OpenNI disabled because libusb-1.0 not found.
CMake Warning at cmake/pcl_targets.cmake:864 (message):
  OpenNI grabber support: not building because OpenNI not found
Call Stack (most recent call first):
  CMakeLists.txt:296 (PCL_ADD_GRABBER_DEPENDENCY)


-- Checking for module 'libusb-1.0'
--   No package 'libusb-1.0' found
-- Could NOT find USB_10 (missing:  USB_10_LIBRARY USB_10_INCLUDE_DIR) 
-- OpenNI 2 disabled because libusb-1.0 not found.
CMake Warning at cmake/pcl_targets.cmake:864 (message):
  OpenNI2 grabber support: not building because OpenNI2 not found
Call Stack (most recent call first):
  CMakeLists.txt:297 (PCL_ADD_GRABBER_DEPENDENCY)


-- Could NOT find FZAPI (missing:  FZAPI_LIBS FZAPI_INCLUDE_DIRS) 
CMake Warning at cmake/pcl_targets.cmake:864 (message):
  Fotonic camera support: not building because FZAPI not found
Call Stack (most recent call first):
  CMakeLists.txt:298 (PCL_ADD_GRABBER_DEPENDENCY)


-- Could NOT find ensenso (missing:  ENSENSO_LIBRARY ENSENSO_INCLUDE_DIR) 
CMake Warning at cmake/pcl_targets.cmake:864 (message):
  IDS-Imaging Ensenso camera support: not building because Ensenso not found
Call Stack (most recent call first):
  CMakeLists.txt:299 (PCL_ADD_GRABBER_DEPENDENCY)


-- Could NOT find davidSDK (missing:  DAVIDSDK_LIBRARY DAVIDSDK_INCLUDE_DIR) 
CMake Warning at cmake/pcl_targets.cmake:864 (message):
  David Vision Systems SDK support: not building because davidSDK not found
Call Stack (most recent call first):
  CMakeLists.txt:300 (PCL_ADD_GRABBER_DEPENDENCY)


-- Could NOT find DSSDK (missing:  DSSDK_LIBRARIES DSSDK_INCLUDE_DIRS) 
CMake Warning at cmake/pcl_targets.cmake:864 (message):
  DepthSense SDK support: not building because DSSDK not found
Call Stack (most recent call first):
  CMakeLists.txt:301 (PCL_ADD_GRABBER_DEPENDENCY)


-- Could NOT find RSSDK (missing:  RSSDK_LIBRARIES RSSDK_INCLUDE_DIRS) 
CMake Warning at cmake/pcl_targets.cmake:864 (message):
  RealSense SDK support: not building because RSSDK not found
Call Stack (most recent call first):
  CMakeLists.txt:302 (PCL_ADD_GRABBER_DEPENDENCY)


-- Checking for module 'metslib'
--   No package 'metslib' found
-- Found ZLIB: /opt/android/sdk/android-ndk-r18b/platforms/android-24/arch-arm64/usr/lib/libz.a (found version "1.2.7") 
-- Could NOT find PNG (missing:  PNG_LIBRARY PNG_PNG_INCLUDE_DIR) 
-- Found Qhull: /opt/ros_android/target/lib/libqhullstatic.a  
-- QHULL found (include: /opt/ros_android/target/include, lib: optimized;/opt/ros_android/target/lib/libqhullstatic.a;debug;/opt/ros_android/target/lib/libqhullstatic.a)
-- Could NOT find PCAP (missing:  PCAP_LIBRARIES PCAP_INCLUDE_DIRS) 
CMake Error at /opt/android/sdk/cmake/3.6.4111459/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find OpenGL (missing: OPENGL_gl_LIBRARY OPENGL_INCLUDE_DIR)
Call Stack (most recent call first):
  /opt/android/sdk/cmake/3.6.4111459/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /opt/android/sdk/cmake/3.6.4111459/share/cmake-3.6/Modules/FindOpenGL.cmake:172 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  cmake/pcl_find_gl.cmake:6 (find_package)
  CMakeLists.txt:414 (include)


-- Configuring incomplete, errors occurred!
See also "/opt/ros_android/libs/pcl/build/CMakeFiles/CMakeOutput.log".
See also "/opt/ros_android/libs/pcl/build/CMakeFiles/CMakeError.log".
/opt/ros_android/scripts/build_library_with_cmake.sh pcl

  /opt/android/sdk/cmake/3.6.4111459/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /opt/android/sdk/cmake/3.6.4111459/share/cmake-3.6/Modules/FindOpenGL.cmake:172 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  cmake/pcl_find_gl.cmake:6 (find_package)
  CMakeLists.txt:414 (include)


-- Configuring incomplete, errors occurred!
See also "/opt/ros_android/libs/pcl/build/CMakeFiles/CMakeOutput.log".
See also "/opt/ros_android/libs/pcl/build/CMakeFiles/CMakeError.log".
/opt/ros_android/scripts/build_library_with_cmake.sh pcl
---
this error I can't relove until now.

**Comment by gongyue666** [comment]
I use the branch kenitic , does it is the release version?

**Comment by jubeira** [comment]
Hi @gongyue666,

What were you doing when you encountered the error? Have you tried https://github.com/Intermodalics/ros_android#quick-installation-with-docker to start with?

Yes, Kinetic is the branch that has to be used.

**Comment by gongyue666** [comment]
yes,l have used it.both two ways Ihave try, get the same many errors.my computer setting is ubuntu 16.04~x86_64 .what should l do now?

**Comment by gongyue666** [comment]
I am sorry, I forget to set patch =1, so the errors comes.so sorry for waste your time.now I have install successfully. good job, many thx~
