### ISSUE TITLE
build cross-compiled system with ANDROID_ABI=armeabi-v7a error

### ISSUE THREAD

**Issue by gongyue666** [Intermodalics/ros_android#115]
hi, today I want to build a cross-compiled environment support **armeabi-v7a**. I modify the config.sh  **from: export ANDROID_ABI=arm64-v8a to :export ANDROID_ABI=armeabi-v7a**
when build poco, comes a error: clang70++: warning: optimization flag '-finline-limit=64' is not supported [-Wignored-optimization-argument]
error: unable to open output file
      '/opt/ros_android/output/libs/poco/XML/obj/Android/armeabi-v7a/debug_static/AbstractNode.o':
      'No such file or directory'
1 error generated.
/opt/ros_android/output/libs/poco/build/rules/compile:35: recipe for target '/opt/ros_android/output/libs/poco/XML/obj/Android/armeabi-v7a/debug_static/AbstractNode.o' failed
make[1]: *** [/opt/ros_android/output/libs/poco/XML/obj/Android/armeabi-v7a/debug_static/AbstractNode.o] Error 1
make[1]: Leaving directory '/opt/ros_android/output/libs/poco/XML'
Makefile:145: recipe for target 'XML-libexec' failed
make: *** [XML-libexec] Error 2
/opt/ros_android/scripts/build_library_with_toolchain.sh poco

how can I build a armeabi-v7a supported cross-compiled environment?

**Comment by jubeira** [comment]
Hi @gongyue666,
The current state of the repository supports only `arm64-v8` ABI as it is now. Some packages and dependencies might build properly for `v7a`, but definitely not all of them.

If you don't need to build _everything_, I'd suggest you to try building a subset of the packages / dependencies; it might be enough for your usecase. If you find that you really need a package or dependency that still fails on `v7a`, feel free to submit a PR with a patch that fixes it.

**Comment by gongyue666** [comment]
ok, thx for your reply, I'll try.
