### ISSUE TITLE
Missing plugins due to inconsistent set of packages

### ISSUE THREAD

**Issue by meyerj** [Intermodalics/ros_android#93]
I found that commenting all those packages in #63 and older commits trigger exceptions in `rospkg.RosPack`, if the set of packages in the workspace is not consistent, which is the case at the moment. In particular, `pluginlib_helper.py` does not find all plugins declared in additional user-defined workspaces.

So if package `a` is not needed on Android by itself, but package `b` depends on it, even though only for some functionality that is not required on Android, we would still have to include `a` or also patch package `b` and remove the dependency on `a` there.

This especially affects most of the `ros*` packages, like `roslaunch`, `rosmaster`, `rosmsg`, ... because other packages in the workspace directly or indirectly depend on it. Some examples:

- `tf2_ros` depends on commented `tf2_py`
- `dynamic_reconfigure` depends on commented `rosservice` depends on `rosmsg`
- `tf_conversions` depends on `python_orocos_kdl`
- Many packages depend on `rostest` which depends on commented `roslaunch` and `rosparam`
- ...

**Comment by ivanpauno** [comment]
In #73 I added plugins finding in an additional workspace.
Usage is ./do_everything output --extends-workspace additional_workspace
I only accepted one more, but it could be extended easily to more than one

**Comment by meyerj** [comment]
Some commented packages like `xacro` or `rosbash` (provides `roscd`) can still be build dependencies of others (e.g. `xacro`) or useful during development even if their build artifacts are not needed at run-time.

**Comment by meyerj** [comment]
> In #73 I added plugins finding in an additional workspace.

Exactly, and that is what I used (in combination with #92), but it does not find all plugins. The script only finds **direct** dependencies of `pluginlib`, `nodelet` or `image_transport_plugins`, but for example not packages providing plugins for `filters` that do not additionally depend on `pluginlib`.

My fix (https://github.com/Intermodalics/ros_android/pull/94/commits/b7dcd194291d31577f7571d282493d2473eab708) was then broken by the fact that the set of packages in `catkin_ws` is inconsistent. I suggest to revert most of the changes in #63 for that reason.

**Comment by jubeira** [comment]
> My fix (PR pending) was then broken by the fact that the set of packages in catkin_ws is inconsistent. I suggest to revert most of the changes in #63 for that reason.

Understood; I'll send a PR tomorrow with the fix.

**Comment by ivanpauno** [comment]
Sounds good, I don't have another way of solving the problem

**Comment by meyerj** [comment]
> Understood; I'll send a PR tomorrow with the fix.

Suggested fix in https://github.com/Intermodalics/ros_android/pull/94.
